spring:
  application:
    name: blog-jdbc

  datasource:
    url: jdbc:postgresql://localhost:5432/blog-jdbc
    username:
    password:
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
